apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-llm
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-llm
  strategy: {}
  template:
    metadata:
      annotations:
        dapr.io/app-id: workflow-llm
        dapr.io/app-port: "8004"
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "59213"
        dapr.io/unix-domain-socket-path: ""
      labels:
        app: workflow-llm
    spec:
      containers:
      - env:
        - name: APP_PORT
          value: "8004"
        - name: DAPR_METRICS_PORT
          value: "59213"
        - name: DEBUG
          value: "true"
        - name: APP_ID
          value: workflow-llm
        - name: APP_CHANNEL_ADDRESS
        - name: OPENAI_API_KEY
          valueFrom: 
            secretKeyRef: 
              name: mcp-secrets
              key: OPENAI_API_KEY
        - name: OPENAI_MODEL
          valueFrom: 
            secretKeyRef: 
              name: mcp-secrets
              key: OPENAI_MODEL
        image: localhost:5001/workflow-llm:latest
        imagePullPolicy: Always
        name: workflow-llm
        ports:
        - containerPort: 8004
        resources: {}
